In [42]:
# data organization libraries
import numpy as np
import pandas as pd

# data visualization libraries
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns

# modeling libraries
from sklearn.linear_model import LinearRegression


In [43]:
fires = pd.read_csv('raw_df.csv')

fires.head()

X  Y  month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area  \
0  1  2      8    5  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0   0.00   
1  5  4      8    2  95.1  141.3  605.8  17.7  26.4  34   3.6   0.0  16.40   
2  6  5      8    3  92.1  111.2  654.1   9.6  16.6  47   0.9   0.0   2.29   
3  6  3      8    4  91.6  138.1  621.7   6.3  18.9  41   3.1   0.0  10.34   
4  4  5      8    0  90.2   99.6  631.2   6.3  21.4  33   3.1   0.0   0.00   

  area_cat temp_bins  
0      0-5       >25  
1    10-50       >25  
2      0-5     15-20  
3    10-50     15-20  
4      0-5     20-25

In [44]:
len(fires)

2652

In [45]:
# create model that trains on all features


In [46]:
#create naive model
# need to split data into X(features) and y(response)

In [47]:
X_df = fires.iloc[:, [0,1,2,3,4,5,6,7,8,9,10,11]]

X_df.head()

X  Y  month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain
0  1  2      8    5  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0
1  5  4      8    2  95.1  141.3  605.8  17.7  26.4  34   3.6   0.0
2  6  5      8    3  92.1  111.2  654.1   9.6  16.6  47   0.9   0.0
3  6  3      8    4  91.6  138.1  621.7   6.3  18.9  41   3.1   0.0
4  4  5      8    0  90.2   99.6  631.2   6.3  21.4  33   3.1   0.0

In [48]:
y_df = fires.iloc[:, [12]]

y_df.head()

area
0   0.00
1  16.40
2   2.29
3  10.34
4   0.00

In [49]:
X = X_df.to_numpy()

X

array([[ 1. ,  2. ,  8. , ..., 41. ,  3.6,  0. ],
       [ 5. ,  4. ,  8. , ..., 34. ,  3.6,  0. ],
       [ 6. ,  5. ,  8. , ..., 47. ,  0.9,  0. ],
       ...,
       [ 5. ,  4. ,  4. , ..., 27. ,  5.8,  0. ],
       [ 6. ,  5. ,  4. , ..., 54. ,  5.8,  0. ],
       [ 6. ,  5. ,  4. , ..., 64. ,  3.1,  0. ]])

In [50]:
y = y_df.to_numpy()

y = y.flatten()

y

array([ 0.  , 16.4 ,  2.29, ...,  0.  , 10.93,  3.35])

In [51]:
# lets do a simple test train split using sklearn
from sklearn.model_selection import train_test_split


In [52]:
# pre split
X.shape, y.shape

((2652, 12), (2652,))

In [53]:
# split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=0)

In [54]:
# post split
X_train.shape, y_train.shape

((2121, 12), (2121,))

In [55]:
# post split
X_test.shape, y_test.shape

((531, 12), (531,))

In [67]:
# need to change 1d y to 2d for fitting
y_train = y_train.reshape(len(y_train), 1)

y_train

array([[ 0.  ],
       [ 9.77],
       [14.68],
       ...,
       [ 4.96],
       [ 1.52],
       [ 0.  ]])

In [90]:
# normalize, i.e. standard scalar
from sklearn.preprocessing import StandardScaler

# scale output

sc_y = StandardScaler()

sc_y.fit(y_train)

ys_train = sc_y.transform(y_train)

In [91]:
#scale input

sc_x = StandardScaler()



# fit scalar

sc_x.fit(X_train)

# standardize X_train and X_test

Xs_train = sc_x.transform(X_train)

Xs_test = sc_x.transform(X_test)




In [92]:
# fit with scalar
mod_sc = LinearRegression().fit(Xs_train, ys_train)

In [93]:
# predict with scalar

y_hat_sc = mod_sc.predict(Xs_test)


# scale back

y_preds = sc_y.inverse_transform(y_hat_sc)





In [94]:
# error
from sklearn.metrics import mean_squared_error

er = mean_squared_error(y_test, y_preds)

er

200.6653586429945

In [89]:
score_sc = ((y_test - y_preds)**2).sum()

score_sc

59112553.61288369

In [85]:
# fit train
model = LinearRegression().fit(X_train, y_train)

In [86]:
# predict
y_hat = model.predict(X_test)



In [87]:
# error

error = mean_squared_error(y_test, y_hat)

error

200.66535864299453

In [88]:
score = ((y_test - y_hat)**2).sum()

score

59112553.61288367

In [31]:
# score
score = model.score(X_test, y_test)

score

0.009302190398110644

In [20]:
# plot residuals
#sns.residplot(x=y_hat,y=y_test)
